# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from backend.proto.shatra.ai.v1 import ai_pb2 as shatra_dot_ai_dot_v1_dot_ai__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shatra/ai/v1/ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub:
    """AI turn: search best move + apply rules in one call.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeAiTurn = channel.unary_unary(
                '/shatra.ai.v1.AiService/ComputeAiTurn',
                request_serializer=shatra_dot_ai_dot_v1_dot_ai__pb2.ComputeAiTurnRequest.SerializeToString,
                response_deserializer=shatra_dot_ai_dot_v1_dot_ai__pb2.ComputeAiTurnResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/shatra.ai.v1.AiService/Health',
                request_serializer=shatra_dot_ai_dot_v1_dot_ai__pb2.HealthRequest.SerializeToString,
                response_deserializer=shatra_dot_ai_dot_v1_dot_ai__pb2.HealthResponse.FromString,
                _registered_method=True)


class AiServiceServicer:
    """AI turn: search best move + apply rules in one call.
    """

    def ComputeAiTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeAiTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeAiTurn,
                    request_deserializer=shatra_dot_ai_dot_v1_dot_ai__pb2.ComputeAiTurnRequest.FromString,
                    response_serializer=shatra_dot_ai_dot_v1_dot_ai__pb2.ComputeAiTurnResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shatra_dot_ai_dot_v1_dot_ai__pb2.HealthRequest.FromString,
                    response_serializer=shatra_dot_ai_dot_v1_dot_ai__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shatra.ai.v1.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shatra.ai.v1.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService:
    """AI turn: search best move + apply rules in one call.
    """

    @staticmethod
    def ComputeAiTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shatra.ai.v1.AiService/ComputeAiTurn',
            shatra_dot_ai_dot_v1_dot_ai__pb2.ComputeAiTurnRequest.SerializeToString,
            shatra_dot_ai_dot_v1_dot_ai__pb2.ComputeAiTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shatra.ai.v1.AiService/Health',
            shatra_dot_ai_dot_v1_dot_ai__pb2.HealthRequest.SerializeToString,
            shatra_dot_ai_dot_v1_dot_ai__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
